In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV
from torch.utils.data import DataLoader, TensorDataset
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import os

In [9]:
data = pd.read_csv('02-14-2018.csv')

In [12]:
data = data[["Dst Port", 'Protocol', "Flow Duration", "Tot Fwd Pkts", "Tot Bwd Pkts", "Label"]]
print(data.head())


scaler = StandardScaler()
data_scaled = scaler.fit_transform(data.drop(['Label'], axis=1))
print("Finished Scaling table")

X = data_scaled
y = data['Label']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print("Finished splitting into training and test")


   Dst Port  Protocol  Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts   Label
0         0         0      112641719             3             0  Benign
1         0         0      112641466             3             0  Benign
2         0         0      112638623             3             0  Benign
3        22         6        6453966            15            10  Benign
4        22         6        8804066            14            11  Benign
Finished Scaling table
Finished splitting into training and test


In [13]:
print("Starting Random Forest Training")
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

Starting Random Forest Training


RandomForestClassifier(random_state=42)

In [16]:
#predicting
print("Starting Random Forest Prediction")
y_pred = model.predict(X_test)

y_pred = y_pred.astype(str)
y_test = y_test.astype(str)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

Starting Random Forest Prediction
[[200369      1      0]
 [     0  57826      0]
 [     0      9  56368]]
                precision    recall  f1-score   support

        Benign       1.00      1.00      1.00    200370
FTP-BruteForce       1.00      1.00      1.00     57826
SSH-Bruteforce       1.00      1.00      1.00     56377

      accuracy                           1.00    314573
     macro avg       1.00      1.00      1.00    314573
  weighted avg       1.00      1.00      1.00    314573

Accuracy: 0.9999682108763308
